# Salesforce auth
sfdc_auth_url: https://test.salesforce.com
sfdc_client_id:
sfdc_client_secret:
sfdc_username:
sfdc_password: 

# JIRA auth
jira_url: http://localhost:8070
jira_username: vokhrimenko@mirantis.com
jira_password: test

# State storage path
storage_dir: /tmp

# JQL for matching issues
jira_issue_jql: project = MY

# Issue field used to hold reference to the SFDC case ID
jira_reference_field: customfield_10100

jira_priority_map:
  Blocker: normal
  Critical: normal
  Major: normal
  Minor: low
  Trivial: low

jira_fallback_priority: normal

jira_solved_statuses:
  - Closed
  - Resolved

jira_possible_status:
  New: New
  Support Investigating: On hold
  Waiting Reporter: Pending
  Waiting Support: Open
  Resolved: Solved
  Closed: Closed

sf_ticket_close_status: Closed

sf_possible_status:
  On hold:
    - Support Investigating
  Pending:
    - Support Investigating
    - Waiting Reporter
  Open:
    - Support Investigating
    - Waiting Reporter
    - Waiting Support
  Solved:
    - Support Investigating
    - Resolved