

# JIRA auth
jira_url: http://localhost:8070
jira_username: SymantecJiraBot
jira_password: test

# State storage path
storage_dir: /tmp

# JQL for matching issues
jira_issue_jql: 'project = MY AND ("Responsible Team" = "Openstack" or "Responsible Team" = "OBS")'

# Issue field used to hold reference to the SFDC case ID
jira_reference_field: customfield_10100

jira_description_field: description

jira_priority_map:
  Blocker: Sev 3
  Critical: Sev 3
  Major: Sev 3
  Minor: Sev 4
  Trivial: Sev 4

jira_fallback_priority: normal

jira_solved_statuses:
  - Closed
  - Resolved

jira_possible_status:
  New: New
  Support Investigating: On hold
  Waiting Reporter: Pending
  Waiting Support: Open
  Resolved: Solved
  Closed: Closed

sf_ticket_close_status: Closed

sf_possible_status:
  On hold:
    - Support Investigating
  Pending:
    - Support Investigating
    - Waiting Reporter
  Open:
    - Support Investigating
    - Waiting Reporter
    - Waiting Support
  Solved:
    - Support Investigating
    - Resolved


# Format used when creating tickets in SF
sf_initial_comment_format: |
  Issue created by {{ issue.fields.creator.displayName }} on {{ issue.fields.created }}
  \\
  {{ issue.fields.description }}
  \\
  ---
  \\
  {{ jira_url }}/browse/{{ issue.key }}


# Format used when creating followup tickets in SF
sf_followup_comment_format: |
  Issue was previously closed but has been reopened

  Issue originally created by {{ issue.fields.creator.displayName }} on {{ issue.fields.created }}
  \\
  {{ issue.fields.description }}
  \\
  ---
  \\
  {{ jira_url }}/browse/{{ issue.key }}


# Format used when creating comments in SF
sf_comment_format: |
  Issue updated by {{ comment.author.displayName }} on {{ comment.created }}
  \\
  {{ comment.body }}

# Format used when creating comments in JIRA
jira_comment_format: |
  *{{ created_by }}, {{ created_at }}*
  \\
  {{ comment }}


# Delimeter used to strip signature from SF comments synced to JIRA
sf_signature_delimeter: ---