

assignee_sf_name:
  - Symantec
  - JiraBot

symantec_assignee_username: Wayland_Shiu

# State storage path
storage_dir: /tmp

# JQL for matching issues
jira_issue_jql: 'project = CFS AND ("Responsible Team" = "Openstack" or "Responsible Team" = "OBS" or zd_reference IS NOT EMPTY) AND SFDC-JIRA~234'

# Issue field used to hold reference to the SFDC case ID
#jira_reference_field: customfield_10100
jira_reference_field: customfield_13000




jira_description_field: description
jira_summary_field: summary

jira_priority_map:
  Blocker: Sev 3
  Critical: Sev 3
  Major: Sev 3
  Minor: Sev 4
  Trivial: Sev 4

jira_fallback_priority: Sev 3

jira_solved_statuses:
  - Closed
  - Resolved

jira_resolution_status:
  name: Fixed

jira_possible_status:
  New: New
  Support Investigating: Open
  Waiting Reporter: Pending
  Waiting Support: Open
  Resolved: Solved
  Closed: Solved

sf_ticket_close_status: Closed
sf_ticket_solve_status:
  - Solved
  - Closed

reference_jira_sf_statuses:
  New:
    Open:
      - Start Investigation
    Pending:
      - Start Investigation
    Solved:
      - Start Investigation
      - Resolve
    Closed:
      - Start Investigation
      - Resolve
    On Hold:
      - Start Investigation
  Waiting Support:
    Pending:
      - Start Investigation
      - Wait Reporter      #Request Information
    Solved:
      - Start Investigation
      - Resolve
    On Hold:
      - Start Investigation
    Closed:
      - Start Investigation
      - Resolve
  Waiting Reporter:
    Solved:
      - Start Investigation
      - Resolve
    On Hold:
      - Start Investigation
    Closed:
      - Start Investigation
      - Resolve
  Support Investigating:
    Pending:
      - Wait Reporter      #Request Information
    Solved:
      - Resolve
    Closed:
      - Resolve
    On Hold:
      - Skip
  Resolved:
    Pending:
      - Start Investigation
      - Wait Reporter
    On Hold:
      - Start Investigation

# Format used when creating tickets in SF
sf_initial_comment_format: |
  Issue created by {{ issue.fields.creator.displayName }} on {{ issue.fields.created }}
  \\
  {{ issue.fields.description }}
  \\
  ---
  \\
  {{ jira_url }}/browse/{{ issue.key }}
  \\
  SF ticket number is {{ case_id }} .
  \\


# String for search and change SF ticket number in description for followed-up ticket
sf_ticket_number_search: "SF ticket number is (.+?) ."

# Format used when creating followup tickets in SF
sf_followup_comment_format: |
  Issue was previously closed but has been reopened
  Issue originally created by {{ issue.fields.creator.displayName }} on {{ issue.fields.created }}
  \\
  ---
  \\
  {{ jira_url }}/browse/{{ issue.key }}


# Format used when creating comments in SF
sf_comment_format: |
  Issue updated by {{ comment.author.displayName }} on {{ comment.created }}
  \\
  {{ comment.body }}

# Format used when creating comments in JIRA
jira_comment_format: |
  *{{ created_by }}, {{ created_at }}*
  \\
  {{ comment }}


# Delimeter used to strip signature from SF comments synced to JIRA
sf_signature_delimeter: ---

# Format used for the subject when creating tickets in SF
sf_summary_format: "[PROJIRA] [{{ issue.key }}] {{ issue.fields.summary }}"